<?php $_configHelper = Mage::helper('bpost_shm/system_config') ?>
<?php if ($_configHelper->getBpostShippingConfig('browser_api_key') != "") { ?>
    <script src="https://maps.googleapis.com/maps/api/js?key=<?php echo $_configHelper->getBpostShippingConfig('browser_api_key') ?>&sensor=false&v=3.17&sensor=false&libraries=geometry,places" type="text/javascript"></script>
<?php } else { ?>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false&v=3.17&sensor=false&libraries=geometry,places" type="text/javascript"></script>
<?php } ?>
<script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/src/infobox.js"></script>